"""initial: jobs, organic_jobs, user_corrections

Revision ID: 9d813f751dc5
Revises: 
Create Date: 2026-02-28 03:18:07.066892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d813f751dc5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_type', sa.String(length=16), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('intent', sa.JSON(), nullable=True),
    sa.Column('precise_spec', sa.JSON(), nullable=True),
    sa.Column('drawing_spec', sa.JSON(), nullable=True),
    sa.Column('drawing_spec_confirmed', sa.JSON(), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('printability_result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('organic_jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('quality_mode', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('printability_result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('user_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('field_path', sa.String(length=256), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=False),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_corrections_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_corrections_job_id'))

    op.drop_table('user_corrections')
    op.drop_table('organic_jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
